a=input('Digite algo: ')
print('O tipo primitivo é: ', type(a))
print('Ele é númerico: ',a.isnumeric())
print('Ele é alfabético: ',a.isalpha())
print('Ele é alfanúmerico: ',a.isalnum())
print('As letras são maiúsculas: ',a.isupper())
print('As letras são minúsculas: ',a.islower())
print('Ele possui espaços em branco: ',a.isspace())
print('Ele está capitalizado: ',a.istitle())