frase=str(input('Digite uma frase: '))
frase=frase.lower().strip()
print('A letra A aparece {} vezes'.format(frase.count('a')))
print('A primeira letra A aparece na posição: {}'.format(frase.find('a')+1))
print('A primeir aletra A aparece na posição: {}'.format(frase.rfind('a')+1))